- src/Components/SelectedFilterDisplay.js
- src/Components/SocialMedia.js
- src/Components/scss/SelectedFilterDisplay.scss
- src/GraphContainer.js
- src/dashboard/DashNavBar.js
Corrected Spaces in Selected Filters
Adjusted Sauti watermark
Adjusted window size in social media
- [ x] My code has been reviewed by at least one peer
- [x ] There are no merge conflicts
> Spaces dashes

- src/Components/themeStyledComponents/atoms/Image.js
> comment out lazy loader

- src/Components/Filters/FilterBox.js
- src/Components/Graph.js
- src/Components/LineGraph/LineTime.js
- src/Components/LineGraph/downloadLine.js
- src/Components/LineGraphHelpers/scale100.js
- src/dashboard/DashData.js
> Theme corrections contact url

- notes.md
- src/Components/Filters/AddFilter.js
- src/Components/Filters/CompareSubsamples.js
- src/Components/GraphParse.js
- src/Components/SocialMedia.js
- src/Components/dataParse.js
- src/Components/reducers/catReducer.js
- src/Components/reducers/rootReducer.js
- src/Components/redux-actions/catLabels.js
- src/dashboard/DashData.js
- src/dashboard/DashNavBar.js
- src/dashboard/QueryGraphLabels.js
frontend pulls in and uses graphlabels from the backend
> Graph labels

- src/Components/Filters/AddFilter.js
- src/Components/Filters/Apply.js
- src/Components/Filters/CompareSubsamples.js
- src/Components/Filters/DataSFilter.js
- src/Components/Filters/FilterBox.js
- src/Components/Filters/FilterCategoryOptions.js
- src/Components/Filters/RenderCheckContainer.js
- src/Components/GraphParse.js
- src/Components/LineGraph/LineFilter.js
- src/Components/LineGraph/LineTime.js
- src/Components/LineGraphHelpers/topChecked.js
- src/Components/Queries2.js
- src/Components/dataParse.js
- src/DataParseHelpers/setCrossedItems.js
- src/GraphContainer.js
- src/dashboard/QueryGraphLabels.js
modify line graph top results.  Top results are now calculated since start of previous year.
> Spinner cleanup top10

- src/Components/themeLanding/landingComponents/Hero.js
- src/Components/themeLanding/landingComponents/Hub.js
- src/Components/themeLanding/landingComponents/LandingDownload.js
- src/Components/themePricing/pricingComponents/Main.js
> page links to pricing, faqs, and sign up pages

- src/Components/Account/Account.js
- src/Components/Account/components/General/General.js
- src/dashboard/DashNavBar.js
- src/dashboard/DashboardAccount/AccountHandler.js
> add state to account.js

- notes.md
- src/Components/Account/Account.js
- src/Components/Account/components/General/General.js
- src/dashboard/DashboardAccount/EditAccount.js
> Account state usestate

- src/dashboard/App.js
> call graphLabels from app.js

- src/Components/Filters/CalendarFilter.js
- src/Components/Filters/CompareSubsamples.js
- src/Components/GraphParse.js
- src/GraphContainer.js
> pass props for calendar

- src/Components/Account/Account.js
- src/dashboard/QueryGraphLabels.js
> add sweet alerts to Account.js and QueryGraphLabels.js

- src/Components/Account/Account.js
- src/Components/LineGraph/downloadLine.js
> add comment on line graph

- src/Components/LineGraph/LineGraph.js
- src/Components/LineGraph/LineTime.js
- src/Components/LineGraph/downloadLine.js
- src/Components/LineGraphButton.js
> add list of filters to download

- src/Components/themePricing/pricingComponents/Main.js
branch join
from Pricing page, when click join, it takes you to signup
> join to signup page

- src/Components/themeLanding/landingComponents/Hero.js
- src/Components/themeLanding/landingComponents/Hub.js
Update frontpage links
get started -> signup
learn more -> pricing
> started -> signup, learn more -> pricing

- src/Components/themeLanding/landingComponents/LandingDownload.js
> update home page links

- src/Components/dataParse.js
- src/DataParseHelpers/setCrossedItems.js
add variable graphLabels
trello [https://trello.com/c/0XmlV2Ir/11-bug-for-when-you-choose-data-series-country-of-residence-compare-data-currency-exchanges](url)
> add graphLabels

- src/Components/themeContact/Contact.js
Add dropdown nature of inquiry to Contact page.
Also required backend update
trello [https://trello.com/c/1l5qycfu/13-contact-page-should-have-nature-of-inquiry-dropdown-sales-data-technical-other](url)
> add dropdown to contact page

- src/Components/Graph.js
trello [https://trello.com/c/h51bK8V5/24-downloaded-excel-sheets-are-showing-undefined-values-remove](url)
update excel spreadsheet
remove undefined
add compare data
> update excel download

- src/Components/Account/components/MyAccount/MyAccount.js
trello [https://trello.com/c/AKtVLTTH/1-accounts-page-needs-to-be-able-to-change-account-settings](url)
Able to change account settings
> Edit account

- src/Components/Account/Account.js
Free accounts are routed to Subcrpitons first
[https://trello.com/c/Fe3xWCnA/2-account-page-needs-to-default-to-account-tab-when-clicking-it-when-logged-in-when-you-are-clicking-from-signup-it-should-goto-su](url)
> free account will see subscription

- src/dashboard/CreateAccount.js
I had to redo the dropdowns.  Seemed all material-ui dropdowns were refreshing the page when you select the arrow down.
trello [https://trello.com/c/ZzSwLli4/15-weird-bug-on-signup-where-dropdown-for-org-causes-screen-to-reset-to-top](url)
> modify dropdowns

- src/Components/Account/Account.js
- src/Components/Account/components/MyAccount/MyAccount.js
Add change plan button to Account page
trello [https://trello.com/c/sqAM3RxN/27-styling-the-account-details-page-change-plan-button](url)
> Account styling

- src/Components/ChoroplethMap/AfricaMap.js
- src/Components/ChoroplethMap/ChoroplethParent.js
- src/Components/GraphButtons.js
- src/Components/LineGraphButton.js
- src/Components/orderedGraphLabels.js
Update map apply button to match Apply button
trello [https://trello.com/c/40G9myFQ/20-to-show-map-results-you-must-click-display-button-lets-tie-this-in-to-apply-button-so-it-automatically-shows-results](url)
> update map Apply button

- src/dashboard/CalendarParent.js
> styling boxes

- README.md
- src/Components/Filters/AddFilter.js
- src/Components/Filters/CalendarFilter.js
- src/Components/Filters/CompareSubsamples.js
- src/Components/Filters/DataSFilter.js
- src/Components/Filters/FilterBox.js
- src/Components/LineGraph/LineFilter.js
- src/Components/LineGraph/LineGraph.js
- src/Components/LineGraph/NoDataLineModal.js
- src/Components/LineGraph/NoDataParent.js
- src/Components/NoDataModal.js
- src/Components/NotLoggedModal.js
- src/Components/reducers/fromNavReducer.js
- src/Components/reducers/rootReducer.js
- src/Components/redux-actions/fromNavAction.js
- src/DataParseHelpers/setCrossedItems.js
- src/dashboard/DashData.js
- src/dashboard/DashLogout.js
- src/dashboard/DataDashHelpers/filters.js
- src/dashboard/Login.js
trello [https://trello.com/c/EKtvZegg/38-bug-when-i-go-to-data-for-the-first-time-it-asks-to-press-apply-and-doesnt-show-the-title-when-logout-and-login-default-search-a](url)
Fix:  on login, default filters search will display in graph and no need to press apply
Fix:  on login, default filters serach will display in graph, and filters in panel will correspond to the default filter search.
> on login press apply will not appear, on logout filters will clear

- src/Components/SocialMedia.js
- src/dashboard/Download.js
- src/dashboard/DownloadModal.js
trello [https://trello.com/c/NeQqZMkS/41-free-users-shouldnt-be-able-to-download-the-data](url)
> free account cannot download
